<a href="https://colab.research.google.com/github/Omarito1980/SIM_YAC_MASAQUIZA_UPSE2023/blob/main/difusividad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:

# Simulacion de yacimientos

In [70]:
import numpy as np

In [71]:
import matplotlib.pyplot as plt

In [72]:
import plotly.express as px

In [73]:
import pandas as pd

In [74]:
P0 = [0, 4000, 4000, 4000, 4000, 0]
dx = 200
dt = 10
tf = 360
tiempo=[0]

In [75]:
columnas=['Celda1','Celda2','Celda3','Celda4']

In [76]:
presiones=pd.DataFrame(columns=columnas)
presiones.loc[0]=P0[1:-1]

In [77]:
presiones.head()

   Celda1  Celda2  Celda3  Celda4
0    4000    4000    4000    4000

In [78]:
P1=P0
for t in range(dt,tf+1,dt):
  tiempo.append(t)
  for i in range(1,len(P0)-1):
    P1[i]=((P0[i-1]-2*P0[i]+P0[i+1])/dx**2)*dt+P0[i]
  P0=P1
  presiones.loc[t/dt]=P0[1:-1]

In [79]:
presiones.head()

          Celda1       Celda2      Celda3       Celda4
0.0  4000.000000  4000.000000  4000.00000  4000.000000
1.0  3999.000000  3999.999750  4000.00000  3999.000000
2.0  3998.000500  3999.999250  3999.99975  3998.000500
3.0  3997.001500  3999.998501  3999.99925  3997.001499
4.0  3996.002998  3999.997502  3999.99850  3996.002998

In [82]:
df=pd.DataFrame(columns=['Presion','Celdas','Tiempo'])
df['Presion']=presiones.to_numpy().flatten(order='F')
df['Celdas']=sorted(columnas*len(tiempo))
df['Tiempo']=tiempo*len(columnas)

In [84]:
df.head()

       Presion  Celdas  Tiempo
0  4000.000000  Celda1       0
1  3999.000000  Celda1      10
2  3998.000500  Celda1      20
3  3997.001500  Celda1      30
4  3996.002998  Celda1      40

In [85]:
df.tail()

         Presion  Celdas  Tiempo
143  3968.246426  Celda4     320
144  3967.262271  Celda4     330
145  3966.278605  Celda4     340
146  3965.295428  Celda4     350
147  3964.312742  Celda4     360